stages:
    - build
    - publish

build:linux-gnu-amd64:
    stage: build
    image: rust
    script:
        - cargo build --release
    artifacts:
        paths:
            - target/release/rua-list

build:linux-musl-amd64:
    stage: build
    image: sseemayer/rust-musl-builder-mingw:latest
    script:
        - cargo build --target=x86_64-unknown-linux-musl --release
    artifacts:
        paths:
            - target/release/x86_64-unknown-linux-musl/rua-list

build:windows-amd64:
    stage: build
    image: sseemayer/rust-musl-builder-mingw:latest
    script:
        - cargo build --target=x86_64-pc-windows-gnu --release
    artifacts:
        paths:
            - target/release/x86_64-pc-windows-gnu/rua-list

rustdoc:
    stage: build
    image: rust
    script:
        - cargo doc
    artifacts:
        paths:
            - target/doc

pages:
    stage: publish
    image: alpine
    dependencies:
        - build:linux-gnu-amd64
        - build:linux-musl-amd64
        - rustdoc
    script:
        - mkdir -p public
        - mv target/doc public/doc
        - mv target/release/rua-list public/rua-list
    artifacts:
        paths:
            - public
    only:
        - master