stages:
    - build
    - publish

build:linux-gnu-amd64:
    stage: build
    image: rust:latest
    script:
        - cargo build --release
    artifacts:
        paths:
            - target/release/rua-list

build:windows-amd64:
    stage: build
    image: rust:latest
    script:
        - apt update -y && apt upgrade -y apt install -y g++-mingw-w64-x86-64
        - rustup target add x86_64-pc-windows-gnu
        - rustup toolchain install stable-x86_64-pc-windows-gnu
        - cargo build --target=x86_64-pc-windows-gnu --release
    artifacts:
        paths:
            - target/release/x86_64-pc-windows-gnu/rua-list

rustdoc:
    stage: build
    image: rust
    script:
        - cargo doc
    artifacts:
        paths:
            - target/doc

pages:
    stage: publish
    image: alpine
    dependencies:
        - build:linux-gnu-amd64
        # - build:linux-musl-amd64
        - rustdoc
    script:
        - mkdir -p public
        - mv target/doc public/doc
        - mv target/release/rua-list public/rua-list
    artifacts:
        paths:
            - public
    only:
        - master